[package]
name = "mako_infinite_shuffle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto_secretbox = "0.1.1"
rand = "0.8.5"